baseURL: "http://localhost:1313/"
languageCode: "en-us"
title: "Strength Edge Tech"
params:
  description: "From Data Overload 
to Clear Coaching Insights"
  contact:
    email: "contact@strength-edge.com"
  # social:
  #   linkedin: "https://linkedin.com/company/strengthedgetech"
  #   twitter: "https://twitter.com/strengthedgetech"
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "contact"
      name: "Contact"
      url: "/contact"
      weight: 2
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 2